spring:
  application:
    name: ifood-test-service-music

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  context-path: /music
  port: 9091