spring:
  application:
    name: gateway

server:
  port: ${PORT:9090}

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    ifood-test-service-music-default:
      path: /music/**
      serviceId: ifood-test-service-music
      stripPrefix: false
      sensitiveHeaders:
    ifood-test-service-music-additional:
      path: /music**
      serviceId: ifood-test-service-music
      stripPrefix: false
      sensitiveHeaders:
    ifood-test-service-spatial-data-default:
      path: /spatial-data/**
      serviceId: ifood-test-service-spatial-data
      stripPrefix: false
      sensitiveHeaders:
    ifood-test-service-spatial-data-additional:
      path: /spatial-data**
      serviceId: ifood-test-service-spatial-data
      stripPrefix: false
      sensitiveHeaders: