spring:
  application:
    name: ifood-test-service-spatial-data

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  context-path: /spatial-data
  port: 9092